---
title: "TCGA"
author: "Julien REY"
output:
  html_document:
    code_folding: hide
    code_download: true
editor_options: 
  chunk_output_type: console
---

########################
Made for docker rna431-2
########################

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, echo = TRUE, message = FALSE, warning = FALSE)
```

# Library

```{r env_loading, include=FALSE}
library(DESeq2)
library(dplyr)
library(ggplot2)

WORKDIR <- "/yourWorkDir/"

INPUT_PATH  <- paste0(WORKDIR, "/Data/")
OUTPUT_PATH = paste0(WORKDIR, "/Output/")

# Set the random number seed
set.seed(1234)
```

# Datas

```{r}
clinical_matrix_TARGET_TALL <- readRDS(file = paste0(INPUT_PATH, "Clinical_matrix_TARGET_TALL_convert.rds"))
RNA_matrix_TARGET_TALL <- readRDS(paste0(INPUT_PATH, "RNA_matrix_TARGET_TALL_convert.rds"))

# Clinical annotation
table(clinical_matrix_TARGET_TALL$detailed_class)

# Check of the patient ID between the two matrix
identical(rownames(clinical_matrix_TARGET_TALL), colnames(RNA_matrix_TARGET_TALL))
```

   HOXA LYL/LMO TAL/LMO     TLX 
     33      18     105      86 
     
# Normalisation with DESeq2

```{r}
TARGET_DESeqTALL <- DESeqDataSetFromMatrix(countData=RNA_matrix_TARGET_TALL, 
                              colData=clinical_matrix_TARGET_TALL, 
                              design= ~ detailed_class)

TARGET_DESeqTALL <- DESeq(TARGET_DESeqTALL)
```

## Violin Plot TARGET P2

```{r}
vsdataTALL <- vst(TARGET_DESeqTALL, blind=FALSE)
mat_vst <- assay(vsdataTALL)

cd9_expr <- mat_vst["CD9", ]

df_cd9 <- data.frame(
  sample = colnames(mat_vst),
  expression = as.numeric(cd9_expr),
  detailed_class = clinical_matrix_TARGET_TALL$detailed_class
)

# Regroup samples from HOXA, LYL/LMO & TLX into one group to compare to Tal/LMO
df_cd9$group_compare <- ifelse(df_cd9$detailed_class == "TAL/LMO", "TAL/LMO", "HOXA-LYL/LMO-TLX")

df_cd9.mean <- df_cd9 %>%
  group_by(group_compare) %>%
  summarise(mean_expression = mean(expression, na.rm = TRUE))

df_cd9. <- df_cd9 %>%
  group_by(group_compare) %>%
  summarise(
    mean_expression = mean(expression, na.rm = TRUE),
    median_expression = median(expression, na.rm = TRUE),
    Q1 = quantile(expression, 0.25, na.rm = TRUE),
    Q3 = quantile(expression, 0.75, na.rm = TRUE),
    sd_expression = sd(expression, na.rm = TRUE)
  )

stat.test <- wilcox.test(df_cd9$expression[df_cd9$group_compare == "TAL/LMO"], df_cd9$expression[df_cd9$group_compare == "HOXA-LYL/LMO-TLX"])

y_max <- max(df_cd9$expression)
y_bar <- y_max + 1.5
y_text <- y_max + 1.8

# Indices of the groups to be compared
x1 <- 1  # TAL/LMO
x2 <- 2  # HOXA-LYL/LMO-TLX

pPlot <- ggplot(df_cd9, aes(x = group_compare, y = expression, fill = group_compare)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1, outlier.shape = NA, show.legend = FALSE) +
  geom_jitter(width = 0.2, size = 1, show.legend = FALSE) +
  scale_fill_manual(values = c("#9BB655FF", "#40E0D0")) +
  
  # Horizontal bar between the two groups
  geom_segment(aes(x = x1, xend = x2, y = y_bar, yend = y_bar), inherit.aes = FALSE) +
  geom_segment(aes(x = x1, xend = x1, y = y_bar, yend = y_bar - 0.1), inherit.aes = FALSE) +
  geom_segment(aes(x = x2, xend = x2, y = y_bar, yend = y_bar - 0.1), inherit.aes = FALSE) +
  
  # Add p-value
  geom_text(aes(x = (x1 + x2)/2,
                y = y_text,
                label = format.pval(stat.test$p.value, digits = 3, scientific = TRUE)),
            inherit.aes = FALSE) +
  
  theme_classic() +
  labs(
    title = "CD9 expression across T-ALL subtypes",
    x = NULL,
    y = "CD9 Expression",
    fill = NULL
  )

pPlot

# ggsave(plot = pPlot,
#        filename = "TCGA_violinplot.pdf",
#        path = OUTPUT_PATH,
#        width = 1600,
#        height = 1750,
#        dpi = 170,
#        units = "px")
```
