---
title: "scRNAseq"
author: "Julien REY"
output:
  html_document:
    code_folding: hide
    code_download: true
editor_options: 
  chunk_output_type: console
---

#########################
Made for docker seurat500
#########################

```{r env_loading, include=FALSE}
# Load packages, data and functions
library(Seurat)
library(mclust)
library(ggpubr)
library(ggrepel)
library(dplyr)
library(clusterProfiler)
library(AnnotationDbi)
library(org.Mm.eg.db)

#Color palette
pal <- viridis::rocket(20, direction = -1)

palette22 <- c(
  "#F781BF", "#B3B3B3", "#4DAF4A", "#D95F02", "#8DA0CB",
  "#1B9E77", "#FF7F00", "#FFD92F", "#FC8D62", "#E5C494",
  "#E41A1C", "#984EA3", "#999999", "#66C2A5", "#A65628",
  "#A6D854", "#66A61E", "#377EB8", "#E1DF33", "#7570B3",
  "#E6AB02", "#E7298A", "#E78AC3")
names(palette22) <- c(0:22)


WORKDIR <- "/yourWorkDir/"

INPUT_PATH  <- paste0(WORKDIR, "Data/")
OUTPUT_PATH = paste0(WORKDIR, "Output/")

# Set the random number seed
set.seed(1234)
```

# Data loading

```{r}
load(paste0(INPUT_PATH, "sickphys_reg.Robj"))

seurat <- sickphys_subset_reg

rm(sickphys_subset_reg)
```

# Figure 1-B
## UMAP Clustering

```{r}
seurat <- FindClusters(seurat, random.seed = 1234, resolution = 2, verbose = FALSE)

seurat@meta.data <- seurat@meta.data[, !colnames(seurat@meta.data) %in% c("nCount_ADT", "nFeature_ADT", "seurat_clusters", "old.ident")]

seurat@meta.data$RNA_snn_res.2 <- factor(seurat@meta.data$RNA_snn_res.2, levels = c(10, 17, 2, 11, 6, 18, 14, 0, 12, 13, 8, 4, 22, 15, 7, 9, 1, 5, 3, 19, 21, 16, 20))

pUmap <- DimPlot(seurat, group.by = "RNA_snn_res.2", cols = palette22)
pUmap

# ggsave(plot = pUmap,
#        filename = "umap_res2.png",
#        path = OUTPUT_PATH,
#        width = 1600,
#        height = 1200,
#        dpi = 170,
#        units = "px",
#        bg = "white")
```

# Differences between Cd9+ en Cd9- physiological

```{r}
Idents(seurat) <- "RNA_snn_res.2"
seurat.phy <- subset(seurat, idents = c(10, 17, 2, 11, 6, 18, 14, 0, 12, 13, 8, 4, 22))
```

```{r}
cd9_vals <- FetchData(seurat.phy, vars = "Cd9")

seurat.phy[["Cd9.test"]] <- ifelse(cd9_vals$Cd9 > 0.5, "Cd9+", "Cd9-")

FeaturePlot(seurat.phy, features = "Cd9")+scale_colour_gradientn(colors = pal, limits = c(0, 3))+ggtitle("Cd9")
```

```{r}
Idents(seurat.phy) <- "Cd9.test"
markers.vs <- FindMarkers(seurat.phy, ident.1 = "Cd9+", only.pos = FALSE, min.pct = 0.01, logfc.threshold = 0.1, random.seed = 1234)
markers.vs$gene <- rownames(markers.vs)


markers.vs.top <- markers.vs %>%
  dplyr::filter(
    avg_log2FC > 0.5 | avg_log2FC < 0.5,
    p_val_adj < 10^-2.5
  ) %>%
  arrange(p_val_adj)


pDotPlot <- DotPlot(seurat.phy, features = unique(unlist(markers.vs.top$gene)))+
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5)+
  scale_colour_gradient2(low = "steelblue", mid = "ivory1", high = "red")+
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white")))+
  RotatedAxis()+
  coord_flip()+
  ggtitle("DEG - Cd9+ vs Cd9- in all physiological cells")

pDotPlot
```

# Tumoral analysis

```{r}
Idents(seurat) <- "RNA_snn_res.2"
seurat.subset <- subset(seurat, idents = c(1, 3, 5, 7, 9, 15, 17, 19))

Idents(seurat.subset) <- "HTO_man"
DGEsick <- FindMarkers(seurat.subset, ident.1 = "sPten* thymus",ident.2 = "sPten* spleen",logfc.threshold = 0, min.pct = 0)

DGEsick$gene <- rownames(DGEsick)
DGEsick <- DGEsick[, c(6, 2, 1, 5, 3, 4)]
rownames(DGEsick) <- NULL

#volcano plot
DGEsick$Significant <- ifelse(DGEsick$p_val_adj < 0.05, ifelse(DGEsick$avg_log2FC > 0,"Tumoral thymus Bonferroni < 0.05","Tumoral spleen Bonferroni < 0.05" ),"Not Significative")

pVolcanoPlot <- ggplot(DGEsick, aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_point(shape = 20, aes(color = Significant),size=2.5)+
   scale_color_manual(values = c("grey","#F8766D","#7CAE00")) +
   theme_bw(base_size = 12) + theme(legend.position = "bottom") +
 geom_label_repel(
    data = subset(DGEsick, p_val_adj < 10^-90),
    aes(label = gene),
    size = 6,
    arrow = arrow(length = unit(0.010, "npc")),
    box.padding = unit(1.5, "lines"),
    point.padding = unit(1, "lines"),
    segment.size = 0.8)+
  ggtitle("Tum - clusters : 1, 3, 5, 7, 9, 15, 17, 19")
pVolcanoPlot

# ggsave(plot = pVolcanoPlot,
#        filename = "volcano_Cd9.pdf",
#        path = OUTPUT_PATH,
#        width = 1500,
#        height = 1300,
#        dpi = 170,
#        units = "px")
```

# Figure 1-C
## Annotation

```{r}
seurat@meta.data$RNA_snn_res.2 <- factor(seurat@meta.data$RNA_snn_res.2, levels = c(16, 20, 10, 2, 11, 18, 6, 0, 12, 8, 4, 14, 13, 22, 9, 7, 15, 17, 19, 3, 5, 1, 21))

Bcells <- c("Cd19")
macro <- c("Cd68")
Tcell_diff <- c("Il2ra", "Cd4", "Cd8a", "Cd8b1", "Cd5")
prolif <- c("Mki67", "Top2a", "Cdk1")
recomb <- c("Rag1", "Rag2")
TCR <- c("Ptcra", "Notch1", "Trac", "Trbc1", "Trbc2", "Tcrg-C1", "Tcrg-C2", "Trdc")
naive <- c("Ccr7", "S1pr1", "Sell")
eff_mem <- c("Cxcr3", "Ccl5")
Tgd <- c("Blk", "Maf")
other <- c("Myc", "Cd9")

known_genes <- c(Bcells, macro, Tcell_diff, prolif, recomb, TCR, naive, eff_mem, Tgd, other)

Idents(seurat) <- "RNA_snn_res.2"

pDotPlot <- DotPlot(seurat, features = known_genes)+
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5)+
  scale_colour_gradient2(low = "steelblue", mid = "ivory1", high = "red")+
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white")))+
  RotatedAxis()+
  coord_flip()+
  ggtitle("Known markers - RNA_snn_res.2")
pDotPlot

# ggsave(plot = pDotPlot,
#        filename = "dotplot_known_markers_res2.pdf",
#        path = OUTPUT_PATH,
#        width = 1450,
#        height = 1350,
#        dpi = 170,
#        units = "px",
#        bg = "white")
```

# Figure 1-F
## Dotplot CD9+ vs CD9- tumoral

```{r}
# Function 2 gaussian mixture model to separate CD9 cells into 2 populations
threshold_2gm <- function(data) {
  gmm <- Mclust(data, G = 2, verbose = FALSE)
    
  weights <- gmm$parameters$pro
  means <- gmm$parameters$mean
  
  if (length(gmm$parameters$variance$sigmasq) == 1) {
    sds <- rep(sqrt(gmm$parameters$variance$sigmasq), 2)
  } else {
    sds <- sqrt(gmm$parameters$variance$sigmasq)
  }
  
  f1 <- function(x) weights[1] * dnorm(x, mean = means[1], sd = sds[1])
  f2 <- function(x) weights[2] * dnorm(x, mean = means[2], sd = sds[2])
  
  # Intersection test
  lower <- min(means)
  upper <- max(means)
  delta_sign <- sign(f1(lower) - f2(lower)) * sign(f1(upper) - f2(upper))
  
  if (delta_sign < 0) {
    intersection <- uniroot(function(x) f1(x) - f2(x), interval = c(lower, upper))$root
  } else {
    warning("No intersection between the two Gaussians within the interval.")
    intersection <- mean(data) + 2 * sd(data)
  }
  return (intersection)
}
```

```{r}
Idents(seurat) <- "RNA_snn_res.2"
seurat.subset <- subset(seurat, ident = c(1, 3, 5, 7, 9, 15, 17, 19))

data <- seurat.subset@assays$RNA@data["Cd9", ]
data <- log1p(data)

threshold <- threshold_2gm(data)

seurat.subset$Cd9_group <- ifelse(log1p(FetchData(seurat.subset, "Cd9")[,1]) > threshold, "Cd9_pos", "Cd9_neg")
```

```{r}
# FindMarkers on Cd9 pop.
Idents(seurat.subset) <- "Cd9_group"
markers <- FindMarkers(seurat.subset, ident.1 = "Cd9_pos", ident.2 = "Cd9_neg", only.pos = FALSE, min.pct = 0.01, logfc.threshold = 0.1, random.seed = 1234)

markers$gene <- rownames(markers)
markers <- markers[, c(6, 2, 1, 5, 3, 4)]
rownames(markers) <- NULL

markers.filter <- markers %>% dplyr::filter(p_val_adj < 0.05)

gene_list <- c("Itga4", "Itgb1", "Itgb7", "H2-K1", "H2-Q7", "Cd160", "Ass1", "Gimap3", "Crtam", "Cd9", "Actg2", "Pla2g16", "Ncf4", "Ms4a4b", "Ly6c2", "Slpi", "Nkg7", "Ap3s1", "Ramp1", "Ano6", "Ccr9", "Cd8b1", "Rmnd5a", "Cd8a")
markers.list <- markers.filter[match(gene_list, markers.filter$gene), ]

pDotPlot <- DotPlot(seurat.subset, features = markers.list$gene)+
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5)+
  scale_colour_gradient2(low = "steelblue", mid = "ivory1", high = "red")+
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white")))+
  RotatedAxis()+
  coord_flip()+
  ggtitle("DEG - genes - tumour")
pDotPlot

# ggsave(plot = pDotPlot,
#        filename = "dotplot_deg.pdf",
#        path = OUTPUT_PATH,
#          width = 620,
#          height = 1050,
#          dpi = 170,
#          units = "px")
```

# GO enrichment

```{r}
markers.filter <- markers %>% dplyr::filter(p_val_adj < 1e-5, abs(avg_log2FC) > 1, pct.1 > 0.25)

universe <- unique(rownames(seurat.subset))
genes_up <- markers.filter$gene[markers.filter$avg_log2FC > 0]
genes_down <- markers.filter$gene[markers.filter$avg_log2FC < 0]

genes_up_entrez <- mapIds(org.Mm.eg.db, keys = genes_up, column = "ENTREZID", keytype = "SYMBOL")
genes_up_entrez <- genes_up_entrez[!is.na(genes_up_entrez)]

genes_down_entrez <- mapIds(org.Mm.eg.db, keys = genes_down, column = "ENTREZID", keytype = "SYMBOL")
genes_down_entrez <- genes_down_entrez[!is.na(genes_down_entrez)]

# Define the universe
universe <- rownames(seurat.subset)
universe_entrez <- mapIds(org.Mm.eg.db, keys = universe, column = "ENTREZID", keytype = "SYMBOL")
universe_entrez <- universe_entrez[!is.na(universe_entrez)]

ego <- enrichGO(
  gene          = genes_up_entrez,
  OrgDb         = org.Mm.eg.db,
  keyType       = "ENTREZID",
  ont           = "ALL",
  universe      = universe_entrez,
  pAdjustMethod = "BH",
  qvalueCutoff  = 0.05,
  readable      = TRUE)

print(dotplot(ego, x = "Count", showCategory = 20) + ggtitle("GO Up-regulated genes"))

ego[ego@result$Description == 'leukocyte cell-cell adhesion', ]


ego <- enrichGO(
  gene          = genes_down_entrez,
  OrgDb         = org.Mm.eg.db,
  keyType       = "ENTREZID",
  ont           = "ALL",
  universe      = universe_entrez,
  pAdjustMethod = "BH",
  qvalueCutoff  = 0.05,
  readable      = TRUE)

print(dotplot(ego, x = "Count", showCategory = 20) + ggtitle("GO Down-regulated genes"))
```

